# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
services:
  app:
    image: romainmiras/ecommmm
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/EcomMMM
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/EcomMMM
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - mynetwork
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    networks:
      - mynetwork
  webserver:
    image: dperson/nginx
    container_name: webserver
    networks:
      - mynetwork
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/azureuser/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy # Wait for the app service to be healthy

networks:
  mynetwork:
    driver: bridge
